### PR TITLE
Di 1113 change to use aws

### PR DESCRIPTION
**Pull request by kjwinfield**
This version has been run on two workbooks to test.
Workbooks added to INCA_workbooks table:
image
Variants added to the INCA AWS table:
image
Variants submitted successfully to ClinVar:
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2)

### CODE REVIEW

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
how long is the whole process ? i noticed that prints send error messages rather than raising exceptions, is that okay? is the user going to be able to notice those prints and follow-up of those errors?

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-:-O9Je4N48wGBteZ3kaan:bu3iep9)* status: all files reviewed, 17 unresolved discussions (waiting on @kjwinfield)

___
*[`pandora.py` line 10 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9Jaq_I4vEG80V-RvgE:-O9Jaq_I4vEG80V-RvgF:b5nsla8) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/pandora.py#L10)):*
> ```Python
> import os.path
> import glob
> from utils.utils import *
> ```

i recommend not using * during imports, it makes the code hard to read especially here since i don't know which function comes from which module.
You can use aliases if you want to reduce the amount of code while providing the source of the function i.e. `import utils.utils as something` or you can list out the functions that you use since you are not using every single function from those modules
___
*[`pandora.py` line 13 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JaaNT4ZVGlZU_A7RQ:-O9JaaNT4ZVGlZU_A7RR:b-2huheo) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/pandora.py#L13)):*
> ```Python
> from utils.clinvar import *
> from utils.database_actions import *
> import numpy as np
> ```

import not used
___
*[`pandora.py` line 158 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9Jc0lB3xwnDrqZ10tN:-O9Jc0lB3xwnDrqZ10tO:b5a59d6) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/pandora.py#L158)):*
> ```Python
>     # These cannot currently be submitted because of a. no clinical indication
>     # in workbook/no affected status and b. a ClinVar API bug
>     exclude = " AND panel != '_HGNC:7527' AND test_code !='R444.1'"
> ```

should that be in your config file? i fear that we might miss the addition or removal of other tests
___
*[`utils/clinvar.py` line 17 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JcpgYAN6PDNERYABl:-O9JcpgZ--umJn3NMMm6:b53dl6s) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/clinvar.py#L17)):*
> ```Python
>         variant_row["comment_on_classification"] = ""
> 
>     if variant_row["ref_genome"] not in ["GRCh37.p13", "GRCh38.p13"]:
> ```

should the reference genomes be in the config as well?
___
*[`utils/clinvar.py` line 77 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9Jd4dEEDrtrv1ptpkM:-O9Jd4dEEDrtrv1ptpkN:b-evzyl4) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/clinvar.py#L77)):*
> ```Python
> 
> 
> def create_header(api_key):
> ```

tiny description would be good, maybe explain that the SP-API-KEY is a AWS specific thing?
___
*[`utils/clinvar.py` line 121 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JdamUC1T408W052s8:-O9JdamV8877KILJOCNA:b-od0mnm) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/clinvar.py#L121)):*
> ```Python
> 
>     print("JSON to submit:")
>     print(json.dumps(clinvar_data, indent=4, default=str))
> ```

isn't that print going to overwhelming? should we have a logging system? should we send alerts through Hermes?
___
*[`utils/clinvar.py` line 164 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JePaT6jdrYpWdAfVB:-O9JePaT6jdrYpWdAfVC:b-na95yg) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/clinvar.py#L164)):*
> ```Python
>     else:
>         print(
>             f"Batch submission has status {status}; not yet processed by "
> ```

i wrote something the discussion about those prints
___
*[`utils/database_actions.py` line 68 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9Jen-j2uZI4bu56OM_:-O9Jen-j2uZI4bu56OMa:b-6yrstb) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/database_actions.py#L68)):*
> ```Python
>         None, adds data to db
>     '''
>     if response.get('id'):
> ```

minor thing, you can shorten that by storing `response.get('id')` in a variable
___
*[`utils/utils.py` line 1 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JfFpH8u0s3r2ISevW:-O9JfFpH8u0s3r2ISevX:b-9q54b5) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L1)):*
> ```Python
> import dxpy
> ```

not used
___
*[`utils/utils.py` line 3 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JfGqw5TgbUVisoPGd:-O9JfGqx85nS-jpBH9n8:b-z2ol12) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L3)):*
> ```Python
> import dxpy
> import re
> from datetime import datetime, date
> ```

datetime not used
___
*[`utils/utils.py` line 51 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JiIWK6p2LClLxhNv1:-O9JiIWK6p2LClLxhNv2:b6o9asb) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L51)):*
> ```Python
>     df_included = get_included_fields(workbook, filename)
>     df_interpret, error = get_report_fields(workbook, config, df_included)
>     if error is not None:
> ```

suggestion for less duplicated code
```
errors = []
errors.append(error)

if not all(errors):
    for error in errors:
        if error is not None:
            add_error_to_db()

    return None

```
___
*[`utils/utils.py` line 86 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9Jl8pgB1rf07pBItE-:-O9Jl8pgB1rf07pBItE0:b-e2nr6w) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L86)):*
> ```Python
>         filename (str): string of workbook name
>     Outputs
>         df_summary (pd.DataFrame): data frame extracted from workbook summary
> ```

you also output an error message 
___
*[`utils/utils.py` line 97 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9Jjh-C7CIEDFPpyCqh:-O9Jjh-C7CIEDFPpyCqi:br5q2r4) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L97)):*
> ```Python
>         condition_names = []
>         test_codes = []
>         for ci in split_ci:
> ```

in order to be more verbose
```
for test_code, condition_name, _ in [ci.split("_") for ci in split_ci]:
    condition_names.append(condition_name)
    test_codes.append(test_code)
```
or 
```
test_code, condition_name, _ = ci.split("_")
```
___
*[`utils/utils.py` line 226 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JlNHO9OXy2ee5Hpfs:-O9JlNHPBiBvbTu-YjEY:b-zgbdei) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L226)):*
> ```Python
>         unique_id = uuid.uuid1()
>         df.loc[row, "local_id"] = f"uid_{unique_id.time}"
>         time.sleep(0.5)
> ```

what is that sleep for
___
*[`utils/utils.py` line 261 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JlfdS809_fsEdi3A4:-O9JlfdS809_fsEdi3A5:b-lk9t4v) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L261)):*
> ```Python
>     if not df_report.empty:
>         error_msg = check_interpret_table(df_report, df_included, config)
>         print(error_msg)
> ```

see discussion message
___
*[`utils/utils.py` line 289 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JmM8oBFjuA-aEfE1X:-O9JmM8oBFjuA-aEfE1Y:b-k7ldzb) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L289)):*
> ```Python
>         all criteria not applied.
>     '''
>     for index, row, in df.iterrows():
> ```

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html
would that accomplish the same thing?
You look for NA or Nones or elements that return false after a `isna` and replace them by `np.nan`
So you should be able to use `fillna` to accomplish the same thing
___
*[`utils/utils.py` line 334 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9Jn1LEAoqzJ6m405jY:-O9Jn1LG3PKkAQeoO4UG:bbcaanc) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L334)):*
> ```Python
>                     acgs[criterion.upper()] = ""
> 
>         c = ','.join([f"{k}_{v}" if v != "" else k for k, v in acgs.items()])
> ```

no single char variable please
is the c for classification?

**Review by kjwinfield — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2)* status: 1 of 6 files reviewed, 16 unresolved discussions (waiting on @Yu-jinKim)

___
*[`pandora.py` line 10 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9Jaq_I4vEG80V-RvgE:-O9KLAoLC2X1VVWAroJi:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/pandora.py#L10)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i recommend not using * during imports, it makes the code hard to read especially here since i don't know which function comes from which module.
You can use aliases if you want to reduce the amount of code while providing the source of the function i.e. `import utils.utils as something` or you can list out the functions that you use since you are not using every single function from those modules
</blockquote></details>

Done.
___
*[`pandora.py` line 13 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JaaNT4ZVGlZU_A7RQ:-O9KLB7Q4YIET4AGALDP:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/pandora.py#L13)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

import not used
</blockquote></details>

Done.
___
*[`pandora.py` line 158 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9Jc0lB3xwnDrqZ10tN:-O9KM27wAJ_uen-hWWNT:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/pandora.py#L158)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

should that be in your config file? i fear that we might miss the addition or removal of other tests
</blockquote></details>

Done.
___
*[`utils/clinvar.py` line 17 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JcpgYAN6PDNERYABl:-O9Kc0ax1SRGWJxET1dc:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/clinvar.py#L17)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

should the reference genomes be in the config as well?
</blockquote></details>

Done.
___
*[`utils/clinvar.py` line 77 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9Jd4dEEDrtrv1ptpkM:-O9Kc3Xv6ICqtxsXouEE:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/clinvar.py#L77)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

tiny description would be good, maybe explain that the SP-API-KEY is a AWS specific thing?
</blockquote></details>

Done.
___
*[`utils/utils.py` line 1 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JfFpH8u0s3r2ISevW:-O9KSc2Z3kCzje7inn87:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L1)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

not used
</blockquote></details>

Done.
___
*[`utils/utils.py` line 3 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JfGqw5TgbUVisoPGd:-O9KScfk8aTfwCvHCciJ:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L3)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

datetime not used
</blockquote></details>

Done.
___
*[`utils/utils.py` line 51 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JiIWK6p2LClLxhNv1:-O9KcLyn8Eu1hiQ71luw:b-t0dkx3) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L51)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

suggestion for less duplicated code
```
errors = []
errors.append(error)

if not all(errors):
    for error in errors:
        if error is not None:
            add_error_to_db()

    return None

```
</blockquote></details>

i have these duplications, so I can return None and exit the function at different times and not bother continuing if there has already been an error
___
*[`utils/utils.py` line 86 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9Jl8pgB1rf07pBItE-:-O9KSe6q4fAqXy61yXDZ:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L86)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

you also output an error message
</blockquote></details>

Done.
___
*[`utils/utils.py` line 97 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9Jjh-C7CIEDFPpyCqh:-O9KMo-r3q2xOcENFtwx:bn08caa) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L97)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

in order to be more verbose
```
for test_code, condition_name, _ in [ci.split("_") for ci in split_ci]:
    condition_names.append(condition_name)
    test_codes.append(test_code)
```
or 
```
test_code, condition_name, _ = ci.split("_")
```
</blockquote></details>

the clinical indication does not always unpack as three variables, it will unpack as two or three depending if it is a panel or a list of HGNC IDs
it can be either Rcode_conditionname_P or _HGNC:id
___
*[`utils/utils.py` line 226 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JlNHO9OXy2ee5Hpfs:-O9KOMCJ4BfakWIsHLNw:ba6n3mn) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L226)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

what is that sleep for
</blockquote></details>

The uuid is based on the time, so that sleep is to make sure that each variant has a unique uuid
see: https://docs.python.org/3/library/uuid.html#uuid.uuid1
___
*[`utils/utils.py` line 289 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JmM8oBFjuA-aEfE1X:-O9KQ9uY-LKJH12o8-qF:bm1coq2) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L289)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html
would that accomplish the same thing?
You look for NA or Nones or elements that return false after a `isna` and replace them by `np.nan`
So you should be able to use `fillna` to accomplish the same thing
</blockquote></details>

it's a bit different to that:
what we are doing is 
1. check if the columns for each ACGS criteria have the string "NA", if they do replace it with nan
2. then if the column for each ACGS criteria is nan, the column for evidence for that criteria should also be nan

e.g.

so neither of these can be done with fillna in both we are adding nan rather than removing it 
___
*[`utils/utils.py` line 334 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9Jn1LEAoqzJ6m405jY:-O9KSp_B5IhYwX5ooh_0:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L334)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

no single char variable please
is the c for classification?
</blockquote></details>

Done.

**Review by kjwinfield — COMMENTED** [review]
the idea is to export error messages into the db, some of those prints were left over from testing and I have converted others into the error message variable

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-:-O9OeaW03JuzPlCPpAPh:bmrvg5w)* status: 1 of 6 files reviewed, 16 unresolved discussions (waiting on @Yu-jinKim)

___
*[`utils/clinvar.py` line 121 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JdamUC1T408W052s8:-O9OeDWm-pWh9kAyZuLd:b-snfhxt) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/clinvar.py#L121)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

isn't that print going to overwhelming? should we have a logging system? should we send alerts through Hermes?
</blockquote></details>

printing this is now optional, it is still useful to have as an option for testing.
___
*[`utils/utils.py` line 261 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JlfdS809_fsEdi3A4:-O9OeQ2G71XE2b9XNh_d:b3axltu) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L261)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

see discussion message
</blockquote></details>

Done. these are not needed and I had them still in from my testing

**Review by kjwinfield — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2)* status: 1 of 6 files reviewed, 16 unresolved discussions (waiting on @Yu-jinKim)

___
*[`utils/clinvar.py` line 164 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JePaT6jdrYpWdAfVB:-O9To6jxE8xfMBkq9Taz:bg9n1y2) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/clinvar.py#L164)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i wrote something the discussion about those prints
</blockquote></details>

most of these are error messages now but i'm leaving some as prints as this will be manually run to start with

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2)* status: all files reviewed, 1 unresolved discussion (waiting on @kjwinfield)

___
*[`utils/utils.py` line 51 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JiIWK6p2LClLxhNv1:-O9Ttb3G-aG5LrSjck9a:bv8sjq1) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L51)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

i have these duplications, so I can return None and exit the function at different times and not bother continuing if there has already been an error
</blockquote></details>

are the previous lines intensive computationally wise?
if not, i think i prefer not having duplicated code

**Review by kjwinfield — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`utils/utils.py` line 51 at r1](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9JiIWK6p2LClLxhNv1:-O9U-7vo1HEWJ898O4za:b-896fix) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/17fa6586a47620fe9565ecc8c40b5f0516778944/utils/utils.py#L51)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

are the previous lines intensive computationally wise?
if not, i think i prefer not having duplicated code
</blockquote></details>

Done.

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2)* status: all files reviewed, 2 unresolved discussions (waiting on @kjwinfield)

___
*[`utils/utils.py` line 52 at r4](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9U-UEH7eJih_2vdUks:-O9U-UEI6IvjkSgQPMeX:b-mumc0l) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/f46eb4d8607256399ee275eb0ee3722cb6c5582f/utils/utils.py#L52)):*
> ```Python
>         errors_to_add = [err for err in errors if err is not None]
>         error_to_add = ", ".join(errors_to_add)
>         add_error_to_db(error_to_add, file, engine)
> ```

don't you need to have the `Return None` after this line?

**Review by kjwinfield — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`utils/utils.py` line 52 at r4](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2#-O9U-UEH7eJih_2vdUks:-O9U0OUA-VoC5ERj2QoB:b-6ygsji) ([raw file](https://github.com/eastgenomics/clinvar_submissions/blob/f46eb4d8607256399ee275eb0ee3722cb6c5582f/utils/utils.py#L52)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

don't you need to have the `Return None` after this line?
</blockquote></details>

Done. yep good point

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/clinvar_submissions/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kjwinfield)

**Pull request merged**
